# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'deel_payments'
version: '1.0.0'
config-version: 2

profile: 'deel_payments'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"

models:
  deel_payments:
    +database: DEEL_ANALYTICS
    
    staging:
      +materialized: view
      +on_schema_change: "fail"

    intermediate:
      +schema: INTERMEDIATE
      +materialized: view
      +on_schema_change: "fail"
    
    marts:
      +schema: MARTS
      +materialized: table
      +on_schema_change: "fail"

    analytics:
      +schema: ANALYTICS
      +materialized: table
    
seeds:
  deel_payments:
    +quote_columns: true

tests:
  deel_payments:
    +store_failures: true
