thelook:
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: gg-data-mesh
      dataset: g_gaiser
      threads: 16
      timeout_seconds: 300
      location: US

    prod:
      type: bigquery
      method: oauth
      project: gg-data-mesh
      dataset: staging
      threads: 16
      timeout_seconds: 300
      location: US

    ci:
      type: bigquery
      method: oauth
      project: gg-data-mesh
      dataset: ci
      threads: 8
      timeout_seconds: 300
      location: US

  target: dev
